In [2]:
# Import NumPy

import numpy as np

In [3]:
with open("hostel_bois.txt","r",encoding="utf-8") as file:
    chat = file.readlines()

print("File loaded successfully")
print("Total lines :",len(chat))

File loaded successfully
Total lines : 3178


In [4]:
# Display first few lines

for i in range(10):
    print(chat[i])

01/04/24, 01:12 - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.

01/04/24, 01:13 - Priya created group "Hostel Bois 4ever"

01/04/24, 01:14 - Priya added you

01/04/24, 01:17 - Rahul: scene fix

01/04/24, 01:17 - Rahul: haan

01/04/24, 01:18 - Rahul: kya scene

01/04/24, 02:13 - Rahul: abhi free hai?

01/04/24, 02:13 - Rahul: abey

01/04/24, 02:14 - Rahul: bhai sun na

01/04/24, 07:46 - Priya: I have extra notes if anyone wants



In [5]:
# Extract Date, Time, Sender and Message
# Using only string methods

messages = []

for line in chat:

    line = line.strip()

    if " - " not in line:
        continue

    first = line.split(" - ",1)

    if len(first) != 2:
        continue

    date_time = first[0]
    remaining = first[1]

    if ": " not in remaining:
        continue

    second = remaining.split(": ",1)

    sender = second[0]
    message = second[1]

    if "," in date_time:

        temp = date_time.split(",")

        date = temp[0].strip()
        time = temp[1].strip()

        messages.append([date,time,sender,message])

print("Messages Extracted :",len(messages))

Messages Extracted : 3174


In [6]:
# Find total participants

participants = set()

for data in messages:
    participants.add(data[2])

print("Total Participants :", len(participants))

print("\nParticipants are:")

for person in participants:
    print(person)

Total Participants : 6

Participants are:
Neha
Rahul
Aman
Priya
Vikas
Karan


In [7]:
# Count messages of each participant

message_count = {}

for data in messages:

    sender = data[2]

    if sender in message_count:
        message_count[sender] = message_count[sender] + 1
    else:
        message_count[sender] = 1

print("Messages sent by each participant:\n")

for person in message_count:
    print(person, ":", message_count[person])

Messages sent by each participant:

Rahul : 953
Priya : 718
Karan : 354
Neha : 635
Aman : 490
Vikas : 24


In [8]:
# Find most active and least active member

highest = 0
lowest = len(messages)

most_active = ""
least_active = ""

for person in message_count:

    if message_count[person] > highest:
        highest = message_count[person]
        most_active = person

    if message_count[person] < lowest:
        lowest = message_count[person]
        least_active = person

print("Most Active Member :", most_active)
print("Messages :", highest)

print()

print("Least Active Member :", least_active)
print("Messages :", lowest)

Most Active Member : Rahul
Messages : 953

Least Active Member : Vikas
Messages : 24


In [9]:
# Calculate average message length

total = 0

for data in messages:
    total = total + len(data[3])

average = total / len(messages)

print("Average Message Length :", round(average,2))

Average Message Length : 52.72


In [10]:
# Find most common words

word_count = {}

for data in messages:

    sentence = data[3].lower()

    words = sentence.split()

    for word in words:

        if word in word_count:
            word_count[word] = word_count[word] + 1
        else:
            word_count[word] = 1

print("Top 10 Most Common Words\n")

for i in range(10):

    highest = 0
    common_word = ""

    for word in word_count:

        if word_count[word] > highest:
            highest = word_count[word]
            common_word = word

    print(common_word, ":", highest)

    word_count[common_word] = -1

Top 10 Most Common Words

the : 1494
and : 1013
i : 759
to : 667
is : 559
was : 400
in : 388
how : 321
this : 313
you : 312


In [11]:
# Count media messages

media = 0

for data in messages:

    if "<Media omitted>" in data[3]:
        media = media + 1

print("Total Media Shared :", media)

Total Media Shared : 32


In [12]:
# Count deleted messages

deleted = 0

for data in messages:

    if "This message was deleted" in data[3]:
        deleted = deleted + 1

print("Deleted Messages :", deleted)

Deleted Messages : 15


In [13]:
# Count system messages

system = 0

for line in chat:

    line = line.strip()

    if " - " in line:

        temp = line.split(" - ",1)

        if ": " not in temp[1]:
            system = system + 1

print("System Messages :", system)

System Messages : 4


In [14]:
# Find most active day

day_count = {}

for data in messages:

    day = data[0]

    if day in day_count:
        day_count[day] = day_count[day] + 1
    else:
        day_count[day] = 1

highest = 0
best_day = ""

for day in day_count:

    if day_count[day] > highest:
        highest = day_count[day]
        best_day = day

print("Most Active Day :", best_day)
print("Messages :", highest)

Most Active Day : 04/05/24
Messages : 76


In [15]:
# Find most active hour

hour_count = {}

for data in messages:

    hour = data[1].split(":")[0]

    if hour in hour_count:
        hour_count[hour] = hour_count[hour] + 1
    else:
        hour_count[hour] = 1

highest = 0
best_hour = ""

for hour in hour_count:

    if hour_count[hour] > highest:
        highest = hour_count[hour]
        best_hour = hour

print("Most Active Hour :", best_hour + ":00")
print("Messages :", highest)

Most Active Hour : 18:00
Messages : 248


In [16]:
# Activity Heatmap

heatmap = np.zeros((24,7),dtype=int)

for data in messages:

    hour = int(data[1].split(":")[0])

    day = int(data[0].split("/")[0]) % 7

    heatmap[hour][day] = heatmap[hour][day] + 1

print("Activity Heatmap")

print(heatmap)

Activity Heatmap
[[10  9  9  5  8  8  8]
 [12 16  7  7 11 12 17]
 [ 4 15 23 11  9 13  8]
 [21 13 16  3  9  7  8]
 [23 12 12 17  9 21 16]
 [ 6  0 16  4  0  3  0]
 [13  3  2  6  2  5  2]
 [ 2  8 16  6  6  8  9]
 [12 15 19 20 21 21 14]
 [14 23 26 28 21 25 14]
 [25 26 22 20 12 27 28]
 [11 20 23 10 15 22 13]
 [21 34 37 25 29 31 16]
 [17 38 26 13 13 31 21]
 [17 38 26 18 24 19 20]
 [17 20 14 31 10 23 16]
 [21 37 34 31 32 10 24]
 [16 37 31 21 23 20 25]
 [43 33 40 31 25 29 47]
 [29 27 33 40 39 24 36]
 [17 35 23 11 32 22 26]
 [24 35 28 44 19  8 19]
 [19 11 18 24 16  6 22]
 [16 19 13 20 49 15 27]]


In [17]:
# Personality of participants

print("Personality Archetypes\n")

for person in message_count:

    count = message_count[person]

    if count >= 700:
        personality = "Spammer"

    elif count >= 500:
        personality = "Conversationalist"

    elif count >= 250:
        personality = "Active Member"

    elif count >= 100:
        personality = "Balanced User"

    else:
        personality = "Ghost Member"

    print(person, ":", personality)

Personality Archetypes

Rahul : Spammer
Priya : Spammer
Karan : Active Member
Neha : Conversationalist
Aman : Active Member
Vikas : Ghost Member


In [18]:
# Final Report

print("\n========== GROUPDNA REPORT ==========\n")

print("Total Messages :", len(messages))

print("Total Participants :", len(participants))

print("Most Active Member :", most_active)

print("Least Active Member :", least_active)

print("Average Message Length :", round(average,2))

print("Media Shared :", media)

print("Deleted Messages :", deleted)

print("System Messages :", system)

print("Most Active Day :", best_day)

print("Most Active Hour :", best_hour + ":00")

print("\nMessages Sent By Participants\n")

for person in message_count:
    print(person, ":", message_count[person])

print("\n========== END OF REPORT ==========")


========== GROUPDNA REPORT ==========

Total Messages : 3174
Total Participants : 6
Most Active Member : Rahul
Least Active Member : Vikas
Average Message Length : 52.72
Media Shared : 32
Deleted Messages : 15
System Messages : 4
Most Active Day : 04/05/24
Most Active Hour : 18:00

Messages Sent By Participants

Rahul : 953
Priya : 718
Karan : 354
Neha : 635
Aman : 490
Vikas : 24

========== END OF REPORT ==========
